# Application
spring.application.name=mastergymsys

# Server
spring.mvc.servlet.path=/api/v1

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/mastergymdb
spring.datasource.username=postgres
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG

# Spring Security
security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}
security.jwt.duration=${JWT_DURATION:86400}

cors.origins=${CORS_ORIGINS:http://localhost:4200,http://localhost:3000,http://localhost:5173}
