# Application
spring.application.name=mastergymsys

# Server
spring.mvc.servlet.path=/api/v1

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/mastergymdb
spring.datasource.username=postgres
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG